Add Mapumental retirement page
mysociety/retirement pull request #3
Opened 2020-04-02 14:41 UTC by sagepe

I've had a stab at doing a simple page for Mapumental. We might want to review the text, particularly the "Why have we closed this site?" section.

2020-04-02 14:44 UTC, sagepe commented
Noting that we can uncomment the link to GitHub once we've open-sourced it.

2020-04-06 11:30 UTC, davea requested changes
One tiny typo, otherwise 👍

2020-04-06 11:30 UTC, davea commented on mapumental_page.html
> +        <p>Maputmental was one of several useful social projects conceived and run by mySociety, <a href="https://www.mysociety.org/projects/">many of which</a> continue to flourish. It just wasn't p
Typo on `Maputmental`

2020-04-06 12:48 UTC, sagepe commented on mapumental_page.html
> +        <p>Maputmental was one of several useful social projects conceived and run by mySociety, <a href="https://www.mysociety.org/projects/">many of which</a> continue to flourish. It just wasn't p
Doh! Cheers, fixed in coming rebase.

2020-04-06 13:03 UTC, merged